"""The LLM boundary (Foundation Phase 6): provider interface, versioned prompts with an
untrusted-content boundary, typed output schemas and schema-validated calls. It has no
side effects: no orders, no risk, no configuration, no tools."""

from stellar.reasoning.contracts import (
    SCHEMAS,
    Argument,
    Basis,
    ClaimLabelling,
    ClaimLabelOutput,
    DebateCaseOutput,
    DebateSide,
    DriverKind,
    MacroAssessmentOutput,
    MacroDriverOutput,
    MarketViewOutput,
    ModelConfidence,
    ObservedChange,
    ReasoningStep,
    Rebuttal,
    Stance,
    SynthesisOutput,
)
from stellar.reasoning.prompts import (
    COMMON_RULES,
    PROMPT_VERSION,
    TEMPLATES,
    PromptTemplate,
    registry_hash,
)
from stellar.reasoning.provider import (
    FailureKind,
    LlmRequest,
    LlmResponse,
    LlmUsage,
    ModelSpec,
    ProviderFailure,
    ReasoningProvider,
    ScriptedProvider,
    UntrustedBlock,
)
from stellar.reasoning.structured import AgentCallRecord, CallStatus, call_structured, fingerprint

__all__ = [
    "COMMON_RULES",
    "PROMPT_VERSION",
    "SCHEMAS",
    "TEMPLATES",
    "AgentCallRecord",
    "Argument",
    "Basis",
    "CallStatus",
    "ClaimLabelOutput",
    "ClaimLabelling",
    "DebateCaseOutput",
    "DebateSide",
    "DriverKind",
    "FailureKind",
    "LlmRequest",
    "LlmResponse",
    "LlmUsage",
    "MacroAssessmentOutput",
    "MacroDriverOutput",
    "MarketViewOutput",
    "ModelConfidence",
    "ModelSpec",
    "ObservedChange",
    "PromptTemplate",
    "ProviderFailure",
    "ReasoningProvider",
    "ReasoningStep",
    "Rebuttal",
    "ScriptedProvider",
    "Stance",
    "SynthesisOutput",
    "UntrustedBlock",
    "call_structured",
    "fingerprint",
    "registry_hash",
]
